name: "Pull Request Labeler"
on:
- pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Update labels based on changed files
      uses: actions/labeler@4b52aec09ba832eb9aecccddbccce644ba9ba69d
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Update labels based on PR title
      id: labeler
      uses: fuxingloh/multi-labeler@fb9bc28b2d65e406ffd208384c5095793c3fd59a # v1.8.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        config-path: .github/multi-labeler.yml
